version: '3.8'

services:
  test_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it2011_ch181_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - ./:/app
    entrypoint: ["/app/entrypoint.sh"]
